sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- 2.0.0
- 1.9.3
- jruby-19mode

before_install:
- gem update --system 2.1.11
- gem install bundler -v 1.12
- bundle --version
- gem --version

before_script:
- bundle list | grep 'bugsnag\|capistrano'
script: bundle exec rake spec

jobs:
  include:
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test bugsnag
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test --without bugsnag
  - stage: test
    env: CAP_2_TEST=false
    install: bundle install --with test bugsnag
  - stage: test
    env: CAP_2_TEST=false
    install: bundle install --with test --without bugsnag
